### ISSUE TITLE
Cannot setcenter if multiple characters have the same name

### ISSUE THREAD

**Issue by CallMeHein** [arishackstv/cubemod#12]
It takes the center of whichever character used setcenter first

**Comment by LucidCypher** [comment]
I also have this problem, and even deleting the first character doesn't allow me to set the center.

**Comment by Xylvier** [comment]
If the character name was **used** previously and the "modcfg.txt" is not cleaned, yes. Every character you create with a name that was used to "/setcenter", will share that center. To get rid of it, just remove the line in the "modcfg.txt" file with the name you would want to reuse. Obviously do not remove it if you still play a character with that name, then rather use a different name.

**Comment by LucidCypher** [comment]
Thank you, Xylvier!  I deleted the save in the saves folder, but that's the file I needed to change.  Much appreciated!
