### ISSUE TITLE
Reins are not working

### ISSUE THREAD

**Issue by ruunix2** [arishackstv/cubemod#14]
I collected all of the movement items over the course of 3 areas. Reins did not appear in the first two areas, and was collected last (in the third area). For some reason, all of the items work fine, but reins will not activate when standing near my pet. The button prompt does not appear, and pressing "E" does nothing, but the item inventory in the top left shows that I already have the reins.

Is this an effect of the mod?

**Comment by Xylvier** [comment]
The button usually set for mounting the pet is "T" as for call/mount pet.
If you have a koala tho you could pick it up with "E".
Riding tho needs "T", that said only if you did not change the controls.
Hope that helps.

**Comment by ruunix2** [comment]
Oops, you're right. For some reason I remember a prompt for the "E" key being there at some point but I guess the T button works. Thank you.
